funding_arb:
  net_edge_bps: 8         # ورود اگر NetEdge ≥ 0.08%
  max_leg_latency_ms: 800
  slippage_bps: 3         # برآورد اسلیپیج هر لِگ
  min_depth_notional: 2000

cash_and_carry:
  basis_bps: 20           # آستانهٔ ورود پس از کسر هزینه‌ها
  max_days: 7

