algo: ppo
policy: MlpPolicy
total_timesteps: 10000
eval_freq: 1000
patience: 5

env:
  max_steps: 100
  risk_file: risk.yml

ppo:
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.95
