algo: sac
policy: MlpPolicy
total_timesteps: 10000
eval_freq: 1000
patience: 5

env:
  max_steps: 100
  risk_file: risk.yml

sac:
  learning_rate: 3e-4
  buffer_size: 100000
  batch_size: 256
  gamma: 0.99
  tau: 0.02
