name: HCOPE Evaluation CI

on: [push, pull_request]

jobs:
  test-hcope:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run HCOPE unit tests
      run: pytest tests/test_hcope.py --maxfail=1 --disable-warnings -q

    - name: Run HCOPE gate tests
      run: pytest tests/test_hcope_gate.py --maxfail=1 --disable-warnings -q
